from functools import update_wrapper

from .densedepth_head_dpm import DenseDepthHead_DPM, DepthBaseDecodeHead
from .densedepth_head_dpm_resnet import DenseDepthHead_DPM_resnet, DepthBaseDecodeHead

from .densedepth_head_base import DenseDepthHead_base,DepthBaseDecodeHead
from .densedepth_head_base_custom_kd import DenseDepthHead_base_custom_kd,DepthBaseDecodeHead

from .densedepth_head_base_custom_kd_resnet import DenseDepthHead_base_custom_kd_resnet,DepthBaseDecodeHead


from .adabins_head import AdabinsHead
from .bts_head import BTSHead
# from .densedepth_head import DenseDepthHead, DepthBaseDecodeHead